### PR TITLE
Create technicalSizing

### PR DESCRIPTION
**Pull request by shantheman**
Pull request?  :)  Not sure if I'm doing this right.

### CODE REVIEW

**Comment by deanpeters** [comment]
No worries @shantheman, there is no right and wrong with this project in terms of using git ... only learning :)

The question itself, love it. I had an experience w/a systems architect in an interview setting who got REALLY grumpy when I asked "why" and drilled into a little of "how" on technical items.  

If you could update this with a rename of the file with an .md extension, I'm cool with it. Dunno how other participants feel.

**Comment by deanpeters** [comment]
Also wondering if we should go ahead and add an enumeration both to the question title and file name?

Something along the lines of technicalSizing.01.md and "Technical Sizing Sanity Check 01" perhaps?

I envision more than one of these gems getting into the repo over time.

**Comment by shantheman** [comment]
OK - made those two changes.

**Review by deanpeters — APPROVED** [review]

**Comment by deanpeters** [comment]
Squash and merge the this branch. Thanks @shantheman !

**Pull request merged**
